num_poses: 1
max_points: 1000
max_burial_percent: 0.7
noise_level: 0.01
camera_radius_range: [1.5, 6.0]
hr_ratio_range: [0.25, 0.5]
theta_range: [0.56, 1.3]
cam_views_per_pose: 20
camera_fov: 1.047
imsize: [512,512]
dataset_loadpath: null
dataset_savepath: 'barrelsynth_data/test_large_noise/data.pkl'