data:
  num_train_poses: 10000
  num_test_poses: 1500
  num_surface_samples: 3000
  max_points: 1000
  max_burial_percent: 0.7
  noise_level: 0.03

train:
  num_epochs: 8000
  save_epoch: 1000
  test_epoch: 1000


optimizer:
  lr: 0.00005
  gamma: 0.9
  step_size: 2000
