data:
  # num_train_poses: 10000
  # num_test_poses: 1500
  max_points: 1000
  # max_burial_percent: 0.7
  # noise_level: 0.03
  # camera_radius_range: [1.5, 6.0]
  # hr_ratio_range: [0.25, 0.5]
  # theta_range: [0.56, 1.3]
  # cam_views_per_pose: 20
  # camera_fov: 1.047
  imsize: [512,512]
  train_dir: 'barrelsynth_data/train_large_noise/'
  test_dir: 'barrelsynth_data/test_large_noise/'

train:
  num_epochs: 100
  save_epoch: 20
  test_epoch: 20

optimizer:
  lr: 0.00005
  gamma: 0.9
  step_size: 2000
